### ISSUE TITLE
Add version number to website

### ISSUE THREAD

**Issue by bntti** [aalto-grades/aalto-grades#610]
- [x] Read / store version number somewhere
  - Automatically update version number on push?
- [x] Show version number on the website
- [ ] Show link to specifically that version of the repository (in the footer)

**Comment by bntti** [comment]
My idea was that the docker compose somehow reads the version from github tags and then puts that to env which gets read during building and placed in the website. Not sure if this is feasible.

But in any case I would like the website version number to match a tag/release version in github.

**Comment by no-comma** [comment]
If we want to, we may be able to use GitHub actions to automatically update the version in `package.json` to match the new version tag when we create releases, but #795 expects the version number to be updated manually.
