### ISSUE TITLE
Add grade priority property (override)

### ISSUE THREAD

**Issue by bntti** [aalto-grades/aalto-grades#700]
- Only one grade can be an override?
    - How does this work with expiry?

**Comment by gubo97000** [comment]
Good question, also regarding the recent thinking we were doing, I guess the basic idea is that you can choose if the override is for that grade instance or forever. 
We should discuss on the difference between a manual grade and an override too.

Use cases needed!

**Comment by no-comma** [comment]
IIRC the main use case was a teacher wanting to deduct points from a student from an A+ source while still wanting to calculate with the best grade in all other cases. But this can be achieved without an override property by just giving priority to manual grades over A+ ones. Is there a need for overrides outside of this case?

**Comment by bntti** [comment]
Tracked in #867
