### ISSUE TITLE
Limited number of manual login attempts

### ISSUE THREAD

**Issue by gubo97000** [aalto-grades/aalto-grades#742]
The idea is simple the implementation is a bit more complex;

From stackOverflow:

> I like storing failures based on two criteria: if a valid user name was used, count a failure for the user name and IP, otherwise just count a failure for the IP. If a specific account is being attacked then it'll lock out the account independent from the specific IP and any single abusive IP gets a site-wide lockout in the process. It is also important to store an explicit expiration time for locks and renew the lock expiration on each attempt.

Or we use captchas but I have no clue if we can legally implement them.

**Comment by no-comma** [comment]
I don't think captchas are the right tool for the job, although from a quick search free/libre and privacy respecting captcha frameworks are available.

**Comment by bntti** [comment]
[Express documentation](https://expressjs.com/en/advanced/best-practice-security.html#prevent-brute-force-attacks-against-authorization) recommends using [node-rate-limiter-flexible](https://www.npmjs.com/package/rate-limiter-flexible)

**Comment by gubo97000** [comment]
Sounds great! Do we want to implement it in memory or postgres? Both should be acceptable solutions.
