### ISSUE TITLE
Re-Introduce maximum grade value for attainments

### ISSUE THREAD

**Issue by gubo97000** [aalto-grades/aalto-grades#779]
There are some cases where having a maximum value of the grade would be useful for catching errors. 
For example typos from the teacher or erroneously importing grades of different attainments.

It is not related to the grading model so it cannot be a node; the output would be Error and not Fail.
From A+ we can get the maximum points. So that would not add any overhead in the creation of A+ attainments.
We can also make it optional so teacher are free to choose.

**Comment by no-comma** [comment]
The maximum grade should be optional and teachers can choose not to input it.
