### ISSUE TITLE
Failed backend tests marked as passed

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/aalto-grades#785]
**To Reproduce**
1. Write backend tests which fail.
2. Push to a PR branch

**Expected behavior**
When backend tests fail, GitHub should mark the "Test and lint server" workflow as failed.

**Actual behavior**
GitHub marks the workflow as passed, even when the tests fail.

**Additional context**
[Example](https://github.com/aalto-grades/aalto-grades/pull/770/commits/99cc09fffe8984bd7713ab5530618a4b33e385ab). Maybe caused by #758?

**Comment by bntti** [comment]
This happens because the pr workflow pipes the docker output and that apparently changes the return code to the return code of the program that runs afterwards. Caused by #758

**Comment by no-comma** [comment]
Should already be fixed in #786
