### ISSUE TITLE
Editing max grade of course parts with A+ sources?

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/aalto-grades#798]
Should we allow editing the max grade of course parts which have A+ sources? This would cause problems if the max points in A+ do not match the max grade we store.

**Comment by bntti** [comment]
We need to be able to either
1. Edit them manually
2. Automatically refresh the max grades from A+ without removing and re-adding the max grade

I think editing them manually is fine, but we can show a warning first.

**Comment by bntti** [comment]
The automatic refresh most likely isn't necessary if we implement the manual editing because I think it's pretty rare that a max grade changes?

**Comment by bntti** [comment]
The user should be able to edit them manually.
