### ISSUE TITLE
Does the react-hooks/exhaustive-deps ESLint rule make sense?

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/aalto-grades#814]
Should we remove it from our config?

**Comment by bntti** [comment]
https://www.reddit.com/r/reactjs/comments/13oy1r5/is_eslint_exhaustive_deps_a_bad_rule_sometimes/

**Comment by bntti** [comment]
https://react.dev/learn/you-might-not-need-an-effect#notifying-parent-components-about-state-changes
