### ISSUE TITLE
Refreshing page resets language

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/aalto-grades#816]
**To Reproduce**
1. Set language to something else
2. Refresh page

**Expected behavior**
The language will stay in the changed one.

**Actual behavior**
The language resets to the original default one.

**Comment by bntti** [comment]
Should be pretty easy to fix by saving the language to localstorage when setting it manually

**Comment by no-comma** [comment]
This was a problem with some local changes I had while trying to fix E2E tests, this bug doesn't occur in dev.
