### ISSUE TITLE
Course Parts Database Schema

### ISSUE THREAD

**Issue by gubo97000** [aalto-grades/aalto-grades#827]
#### course_parts table
- id
- name
- expire_date /*optional*/
- course_id

#### course_parts -> (course_)task table
- course_part

#### grading_model
- course_part_id
    - (Somehow validate uniqueness if not null)

**Comment by bntti** [comment]
How to handle `exportedToSisu`?

**Comment by gubo97000** [comment]
> How to handle `sisuExportDate`? How do we know if a course part grade has been exported? Do we just look at the course tasks? What about when calculating new grades do we use the best not yet exported or can we reuse ones that have been exported to improve our grade?

If I remember correctly the problem is that students can retake a course, but cannot use any of the course parts that were used for the previous grade right? This is quite a pickle, expiration date can be useful but is just an hacky way to stop the re-use of grades... i guess that if we have a solution for grades, it would cascade also on course parts.

**Comment by bntti** [comment]
Conversation continued in #840
